


version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
        - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
        - NEXTAUTH_GITHUB_ID=${NEXTAUTH_GITHUB_ID}
        - NEXTAUTH_GITHUB_SECRET=${NEXTAUTH_GITHUB_SECRET}
        - DATABASE_URL=${DATABASE_URL}
        - RESEND_API_KEY=${RESEND_API_KEY}
        - EMAIL_FROM=${EMAIL_FROM}
        - SENDGRID_API=${SENDGRID_API}
        - STRIPE_API_KEY=${STRIPE_API_KEY}
        - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
        - NEXTAUTH_URL=${NEXTAUTH_URL}
        - NEXT_PUBLIC_STRIPE_PRO_MONTHLY_PLAN_ID=${NEXT_PUBLIC_STRIPE_PRO_MONTHLY_PLAN_ID}
        - NEXT_PUBLIC_STRIPE_PRO_YEARLY_PLAN_ID=${NEXT_PUBLIC_STRIPE_PRO_YEARLY_PLAN_ID}
        - NEXT_PUBLIC_STRIPE_BUSINESS_MONTHLY_PLAN_ID=${NEXT_PUBLIC_STRIPE_BUSINESS_MONTHLY_PLAN_ID}
        - NEXT_PUBLIC_STRIPE_BUSINESS_YEARLY_PLAN_ID=${NEXT_PUBLIC_STRIPE_BUSINESS_YEARLY_PLAN_ID}
      tags: 
        - ${REGISTRY}/${IMAGE_NAME}/frontend:latest
        - ${REGISTRY}/${IMAGE_NAME}/frontend:${GITHUB_SHA}

    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - NEXTAUTH_GITHUB_ID=${NEXTAUTH_GITHUB_ID}
      - NEXTAUTH_GITHUB_SECRET=${NEXTAUTH_GITHUB_SECRET}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - EMAIL_FROM=${EMAIL_FROM}
      - SENDGRID_API=${SENDGRID_API}
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
        - INFLUXDB_ORG=${INFLUXDB_ORG}
        - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
        - INFLUXDB_URL=${INFLUXDB_URL}
      tags: 
        - ${REGISTRY}/${IMAGE_NAME}/backend:latest
        - ${REGISTRY}/${IMAGE_NAME}/backend:${GITHUB_SHA}
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - INFLUXDB_URL=${INFLUXDB_URL}
    restart: unless-stopped

networks:
  app-network:
    driver: bridge