FROM node:18-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the code
COPY . .

# Install only production dependencies
RUN npm ci --only=production

# Set environment variables
ENV NODE_ENV production


# Start the app
CMD ["node", "server.js"]