FROM telegraf:latest

# Set the working directory
WORKDIR /etc/telegraf

# Copy the configuration file into the container
COPY ./telegraf.conf /etc/telegraf/telegraf.conf

# Set the permissions
RUN chmod 644 /etc/telegraf/telegraf.conf

# Expose necessary ports
EXPOSE 5050

# Start Telegraf
CMD ["telegraf"]
