name: testing Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
    debug:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with: 
                context: .

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '18'
            - name: Install Dependencies
              run: npm install
              
            - name: Generate Contentlayer
              run: npm run contentlayer build

            - name: Debug Contentlayer
              run: |
                npm run contentlayer build
                ls -la .contentlayer/generated
                cat .contentlayer/generated/index.mjs